### ISSUE TITLE
老哥，提个BUG

### ISSUE THREAD

**Issue by liaoqiArno** [linzhenyuyuchen/Others#1]
![image](https://user-images.githubusercontent.com/29945921/50583811-7746cf00-0ea6-11e9-92e1-ad6894753ef4.png)

安装这个版本，把中文版复制到lib里，可以显示中文了，但是设置打不开，没有反应！

**Comment by linzhenyuyuchen** [comment]
原因应该是软件的版本和语言包版本不同。
现在用的是学校邮箱申请的版本，后面有解决方法更新。
